command mini <text>:
	trigger:
		set {_command::*} to arg 1 parsed as "register ctf %text%" 
		if {_command::1} is set:
			send "register trigger: register ctf %{_command::1}%" to sender
			exit
		set {_command::*} to arg 1 parsed as "join ctf %text%"
		if {_command::1} is set:
			send "join trigger: join ctf %{_command::1}%" to sender
			exit
		send "Correct usage: /mini [register|join] [ctf] [game name]"